server:
  port: 8891

########################
jwt:
  header: jwt-token
  cookie: jwt-token
  type: jwt-type
  # 24*60*60  一天内过期
  expiration: 1296000000
  refresh:
    # 24*60*60*15
    expiration: 1296000
  secret: eugene
